### ISSUE TITLE
Tutorial I letter omission

### ISSUE THREAD

**Issue by jazz7787** [chrishah/MITObim#19]
Hi Chris,

regarding Tutorial I part :
Would you change the 'data = reference.fa' in the manifest file to 'reference.fasta'? First assembly does not run if the file extension is not changed. Not all systems recognize the difference and it could save users like myself a bit of time on troubleshooting :)

Thanks,
Radu

**Comment by chrishah** [comment]
Hi Radu,

Sorry for the inconvenience! 

With MIRA 4.0.2, if you specify your reference as `something.fasta` in the manifest file and MIRA can't find the file `something.fasta` __and__  a corresponding file called `something.fasta.qual` (which you don't usually have), MIRA will crash. The extension `*.fasta` makes MIRA expect the `*.fasta.qual` file to be present. Using a file with prefix `*.fa` tells MIRA to not bother to look for the quality file and it will happily run if only the `*.fa` file is present.

Not sure what the issue was in your case. Maybe a MIRA version problem? Sorry again for the inconvenience. Closing this. Reopen if necessary.

cheers,
Christoph
